(()=>{
  'use strict';
  const VERSION='1';
  const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();
  let managementDemo;
  let moduleBlocker;
  function ensureModuleBlocker(){if(moduleBlocker)return moduleBlocker;moduleBlocker=document.createElement('div');moduleBlocker.className='gestor-module-blocker';moduleBlocker.hidden=true;document.body.appendChild(moduleBlocker);return moduleBlocker}
  function positionModuleBlocker(){const frame=document.getElementById('contentFrame');if(!moduleBlocker||moduleBlocker.hidden||!frame)return;const rect=frame.getBoundingClientRect();Object.assign(moduleBlocker.style,{left:`${rect.left}px`,top:`${rect.top}px`,width:`${rect.width}px`,height:`${rect.height}px`})}
  function showRealModule(url){hideManagementDemo();const frame=document.getElementById('contentFrame');if(!frame)return;const current=(frame.getAttribute('src')||'').split('?')[0];if(frame.hidden||current!==url)window.portalNavigate?.(url);ensureModuleBlocker().hidden=false;frame.addEventListener('load',positionModuleBlocker,{once:true});setTimeout(positionModuleBlocker,80)}
  function showHomeForTour(){hideManagementDemo();if(moduleBlocker)moduleBlocker.hidden=true;window.portalNavigate?.('home')}
  function ensureManagementDemo(){
    if(managementDemo)return managementDemo;
    managementDemo=document.createElement('div');
    managementDemo.className='gestor-management-demo';
    managementDemo.hidden=true;
    managementDemo.innerHTML=`<section class="gestor-demo-screen gestor-demo-justifications" hidden>
      <header class="gestor-demo-topbar"><span class="gestor-demo-back">←</span><div><small>GESTÃO 360°</small><h2>Validação de justificativas</h2></div><button disabled>↻ Atualizar</button></header>
      <div class="gestor-demo-period"><strong>Período</strong><span>Mês atual</span><span>Ano atual</span></div>
      <div class="gestor-demo-kpis"><article class="is-active"><small>AGUARDANDO VALIDAÇÃO</small><strong>3</strong><span>ainda não regularizam a meta</span></article><article><small>APROVADAS</small><strong>1</strong><span>crédito aplicado à meta</span></article><article><small>REJEITADAS</small><strong>1</strong><span>escola permanece na prioridade</span></article></div>
      <div class="gestor-demo-panel"><header><div><h3>Justificativas registradas</h3><p>Confira a escola, o período e o motivo antes de decidir.</p></div><span class="gestor-demo-search">⌕ Escola, supervisor ou motivo...</span></header><div class="gestor-demo-filters"><b>Pendentes</b><span>Todas</span><span>Aprovadas</span><span>Rejeitadas</span></div><div class="gestor-demo-row"><div><strong>Escola de demonstração</strong><small>Supervisor responsável</small></div><div><small>REFERÊNCIA DA META</small><strong>Mês atual · 1 crédito</strong></div><div class="gestor-demo-reason"><small>MOTIVO INFORMADO</small><strong>Justificativa apresentada pelo supervisor</strong></div><div class="gestor-demo-decisions"><em>AGUARDANDO</em><span><button disabled>✓ Aprovar</button><button disabled>× Rejeitar</button></span></div></div></div>
    </section>
    <section class="gestor-demo-screen gestor-demo-priority" hidden>
      <header class="gestor-demo-topbar"><span class="gestor-demo-back">←</span><div><small>GESTÃO 360°</small><h2>Prioridades de acompanhamento</h2></div><span><button disabled>↻ Atualizar</button><button disabled>↓ Extrair CSV</button></span></header>
      <div class="gestor-demo-rule"><b>15</b><span><strong>Regra inteligente de acompanhamento</strong><small>Identifica escolas abaixo da meta, sem visita recente ou com validações pendentes.</small></span></div>
      <div class="gestor-demo-kpis gestor-demo-priority-kpis"><article class="is-active"><small>PRIORIDADES CRÍTICAS</small><strong>54</strong><span>abaixo da meta e sem justificativa</span></article><article><small>SEM VISITA +15 DIAS</small><strong>51</strong><span>inclui escolas nunca visitadas</span></article><article><small>AGUARDANDO VALIDAÇÃO</small><strong>3</strong><span>registros pendentes ou em análise</span></article><article><small>DENTRO DA REGRA</small><strong>2</strong><span>meta ou justificativa regular</span></article></div>
      <div class="gestor-demo-panel gestor-demo-priority-table"><header><div><h3>Escolas que exigem atenção</h3><p>Use a pesquisa e as classificações para investigar o cenário.</p></div><span class="gestor-demo-search">⌕ Pesquisar escola ou classificação...</span></header><div class="gestor-demo-filters"><b>Todas</b><span>Meta não atingida</span><span>Sem visita +15 dias</span><span>Aguardando validação</span><span>Justificadas</span></div><div class="gestor-demo-table-head"><span>ESCOLA</span><span>ÚLTIMA VISITA</span><span>REALIZADAS</span><span>META</span><span>CLASSIFICAÇÃO</span></div><div class="gestor-demo-table-row"><strong>Escola de demonstração</strong><span>Nunca visitada</span><span>0</span><span>2</span><span><em>Meta não atingida</em> <em>Sem visita +15 dias</em></span></div></div>
    </section>
    <section class="gestor-demo-screen gestor-demo-module" hidden>
      <header class="gestor-demo-topbar gestor-module-demo-header"><span class="gestor-demo-back">←</span><div><small>GESTÃO 360°</small><h2 id="gestorModuleTitle">Módulo</h2><p id="gestorModuleSubtitle"></p></div><button disabled>↓ Exportar análise</button></header>
      <div class="gestor-demo-period gestor-module-demo-period"><strong>Período e filtros</strong><span>Mês atual</span><span>Ano atual</span><span id="gestorModuleFilter">Todos</span></div>
      <div class="gestor-demo-kpis gestor-module-demo-kpis" id="gestorModuleKpis"></div>
      <div class="gestor-demo-panel gestor-module-demo-content"><header><div><h3 id="gestorModulePanelTitle">Detalhamento</h3><p id="gestorModulePanelText"></p></div><span class="gestor-demo-search">⌕ Pesquisar na análise...</span></header><div class="gestor-module-visual" id="gestorModuleVisual"></div></div>
    </section>`;
    document.body.appendChild(managementDemo);
    return managementDemo;
  }
  function showManagementDemo(name){ensureManagementDemo();managementDemo.hidden=false;managementDemo.querySelectorAll('.gestor-demo-screen').forEach(screen=>screen.hidden=!screen.classList.contains(`gestor-demo-${name}`))}
  function showJustificationDemo(){showManagementDemo('justifications')}
  function showPriorityDemo(){showManagementDemo('priority')}
  const moduleDefinitions={
    panorama:{title:'Panorama mensal',subtitle:'Visão consolidada das visitas, status e resultados do mês.',filter:'Todos os supervisores',kpis:[['PLANEJADAS','12','agenda do período'],['VISITADAS','8','visitas concluídas'],['JUSTIFICADAS','2','ausências justificadas'],['ADIADAS','1','serão reagendadas'],['CANCELADAS','1','não realizadas']],panel:'Calendário e relatório analítico',panelText:'Cada dia reúne os registros com a letra e a cor padronizadas.',visual:'calendar'},
    history:{title:'Histórico de visitas',subtitle:'Acontecimentos organizados por data, supervisor e escola.',filter:'Todos os registros',kpis:[['REGISTROS','24','no período'],['SUPERVISORES','8','com atividade'],['ESCOLAS','18','alcançadas'],['REALIZADAS','16','visitas concluídas']],panel:'Linha do tempo das atividades',panelText:'Consulte quem visitou, qual escola recebeu a visita e o que foi registrado.',visual:'timeline'},
    supervisors:{title:'Supervisores × planejamento',subtitle:'Planejamento, execução e cobertura das escolas por supervisor.',filter:'Todos os supervisores',kpis:[['PLANEJADAS','15','visitas previstas'],['REALIZADAS','10','visitas concluídas'],['COBERTURA','67%','do planejamento'],['ESCOLAS','22','unidades alcançadas']],panel:'Desempenho por supervisor',panelText:'Compare planejado, realizado, metas e distribuição semanal.',visual:'bars'},
    schools:{title:'Escolas × planejamento',subtitle:'Acompanhamento mensal das escolas, visitas e metas.',filter:'Todas as escolas',kpis:[['ESCOLAS','58','cadastradas'],['COM VISITA','21','no período'],['SEM VISITA','37','no período'],['META ATINGIDA','18','escolas regulares']],panel:'Detalhamento por escola',panelText:'Identifique planejamento, visitas realizadas, extras e escolas críticas.',visual:'schools'},
    goals:{title:'Metas dos supervisores',subtitle:'Meta mensal, execução, projeção e resultados.',filter:'Todos os supervisores',kpis:[['META DO MÊS','25','visitas previstas'],['REALIZADO','10','visitas concluídas'],['DESEMPENHO','40%','da meta atingida'],['FALTAM','15','visitas para a meta']],panel:'Desempenho por supervisor',panelText:'A meta semanal é calculada a partir da meta mensal configurada.',visual:'goals'},
    filters:{title:'Filtros de vistoria',subtitle:'Consulta detalhada dos registros escolares.',filter:'Todo o período',kpis:[['REGISTROS','24','encontrados'],['REALIZADAS','16','concluídas'],['JUSTIFICADAS','3','com motivo'],['OUTROS STATUS','5','adiadas ou canceladas']],panel:'Registros encontrados',panelText:'Combine supervisor, escola, tipo, status, período e ações realizadas.',visual:'records'}
  };
  function renderModuleDemo(name){
    const data=moduleDefinitions[name];if(!data)return;
    showManagementDemo('module');
    managementDemo.dataset.module=name;
    managementDemo.querySelector('#gestorModuleTitle').textContent=data.title;
    managementDemo.querySelector('#gestorModuleSubtitle').textContent=data.subtitle;
    managementDemo.querySelector('#gestorModuleFilter').textContent=data.filter;
    managementDemo.querySelector('#gestorModuleKpis').innerHTML=data.kpis.map((item,i)=>`<article class="${i===0?'is-active':''}"><small>${item[0]}</small><strong>${item[1]}</strong><span>${item[2]}</span></article>`).join('');
    managementDemo.querySelector('#gestorModulePanelTitle').textContent=data.panel;
    managementDemo.querySelector('#gestorModulePanelText').textContent=data.panelText;
    managementDemo.querySelector('#gestorModuleVisual').innerHTML=data.visual==='calendar'?'<div class="gestor-demo-calendar">'+Array.from({length:14},(_,i)=>`<span><b>${i+1}</b>${[3,7,10].includes(i)?'<em>P 2 · V 1</em>':''}</span>`).join('')+'</div>':data.visual==='timeline'?'<div class="gestor-demo-timeline"><article><b>25 AGO</b><span><strong>Escola de demonstração</strong><small>Supervisor · Visita realizada · Atividade registrada</small></span></article><article><b>24 AGO</b><span><strong>Outra escola</strong><small>Supervisor · Justificativa informada</small></span></article></div>':data.visual==='bars'?'<div class="gestor-demo-bars"><span style="--h:72%">Supervisor A</span><span style="--h:48%">Supervisor B</span><span style="--h:86%">Supervisor C</span><span style="--h:61%">Supervisor D</span></div>':data.visual==='schools'?'<div class="gestor-demo-records"><b>ESCOLA</b><b>PLANEJADAS</b><b>REALIZADAS</b><b>META</b><span>Escola A</span><span>2</span><span>2</span><em>Em dia</em><span>Escola B</span><span>2</span><span>0</span><em>Atenção</em></div>':data.visual==='goals'?'<div class="gestor-demo-records"><b>SUPERVISOR</b><b>VISITAS</b><b>META</b><b>DESEMPENHO</b><span>Supervisor A</span><span>8</span><span>10</span><em>80%</em><span>Supervisor B</span><span>4</span><span>8</span><em>50%</em></div>':'<div class="gestor-demo-records"><b>DATA</b><b>SUPERVISOR</b><b>ESCOLA</b><b>STATUS</b><span>25/08</span><span>Supervisor A</span><span>Escola A</span><em>Realizada</em><span>24/08</span><span>Supervisor B</span><span>Escola B</span><em>Justificada</em></div>';
  }
  const showPanoramaDemo=()=>renderModuleDemo('panorama');
  const showHistoryDemo=()=>renderModuleDemo('history');
  const showSupervisorsDemo=()=>renderModuleDemo('supervisors');
  const showSchoolsDemo=()=>renderModuleDemo('schools');
  const showGoalsDemo=()=>renderModuleDemo('goals');
  const showFiltersDemo=()=>renderModuleDemo('filters');
  function hideManagementDemo(){if(managementDemo)managementDemo.hidden=true}
  const configs={
    'index.html':[
      {selector:'#loginScreen',title:'Acesso ao Gestor-ESE',text:'Entre usando o identificador administrativo fornecido pela gestão e sua senha.'},
      {selector:'#loginEmail',title:'Usuário administrativo',text:'Digite somente o usuário recebido, por exemplo admteste. Não é necessário informar o endereço de e-mail completo.'},
      {selector:'#loginPassword',title:'Senha',text:'Informe sua senha com atenção. Por segurança, ela não é exibida na tela.'},
      {selector:'#btnEmailLogin',title:'Entrar no sistema',text:'Depois de preencher os campos, use este botão para validar o acesso ao portal.'},
      {selector:'.ure-sidebar',title:'Menu principal',text:'O menu organiza a Visão geral, os cadastros e os módulos de gestão. Ele também pode ser recolhido para ampliar a área de trabalho.'},
      {selector:'.ure-nav',title:'Navegação do portal',text:'Use estes atalhos para acessar cadastros, metas, correções de status, localização das escolas e a Equipe ESE.'},
      {selector:'#openAdministratorRegistry',title:'Administradores',text:'Somente o administrador master visualiza esta opção e pode preparar novos acessos administrativos.',tip:'Outros administradores não podem cadastrar administradores nem supervisores.'},
      {selector:'#openSupervisorRegistry',title:'Supervisores',text:'O administrador master prepara supervisores, vincula o perfil ao acesso e organiza as escolas acompanhadas.'},
      {selector:'#openSchoolRegistry',title:'Cadastro de escolas',text:'Cadastre escolas e gerencie os vínculos com um ou mais supervisores sem substituir vínculos existentes.'},
      {selector:'.ure-user',title:'Conta conectada',text:'Confira o nome e o perfil atual. O ícone de saída encerra o acesso com segurança.',tip:'Sempre saia do portal ao terminar o trabalho em computadores compartilhados.'},
      {selector:'.ure-topbar',title:'Visão geral',text:'Esta é a página inicial da gestão. Aqui você acompanha os principais números e acessa rapidamente todas as análises.'},
      {selector:'#searchOpenButton',title:'Busca em tempo real',text:'Pesquise registros por supervisor, escola, status, ação ou autor. A consulta também pode ser aberta com Ctrl + K.'},
      {selector:'.ure-primary-action[data-url="DMC.html"]',prepare:showHomeForTour,title:'Ver panorama mensal',text:'Este botão abre a visão consolidada do mês, reunindo planejamento, visitas e status.'},
      {selector:'#contentFrame',prepare:()=>showRealModule('DMC.html'),title:'Panorama mensal',text:'Nesta tela real do portal você escolhe o período e acompanha visitas planejadas, realizadas, justificadas, adiadas e canceladas.'},
      {selector:'#contentFrame',prepare:()=>showRealModule('DMC.html'),title:'Calendário e indicadores',text:'Os cartões resumem cada status. No calendário, cada dia reúne os registros com as mesmas letras e cores usadas em todo o sistema.'},
      {selector:'#contentFrame',prepare:()=>showRealModule('DMC.html'),title:'Relatório analítico',text:'Alterne entre calendário e relatório analítico quando precisar consultar os registros com mais detalhes.'},
      {selector:'.ure-secondary-action[data-url="historico.html"]',prepare:showHomeForTour,title:'Histórico',text:'Este botão abre a consulta de todos os acontecimentos registrados no sistema.'},
      {selector:'#contentFrame',prepare:()=>showRealModule('historico.html'),title:'Histórico de visitas',text:'Nesta página você escolhe data, supervisor ou escola para reconstruir o histórico das atividades realizadas.'},
      {selector:'#contentFrame',prepare:()=>showRealModule('historico.html'),title:'Filtros do histórico',text:'Combine os filtros para localizar um acontecimento específico ou acompanhar toda a trajetória de uma escola ou supervisor.'},
      {selector:'#contentFrame',prepare:()=>showRealModule('historico.html'),title:'Linha do tempo',text:'Cada resultado informa data, escola, supervisor, status e o conteúdo registrado na atividade.'},
      {selector:'.ure-orbit',prepare:showHomeForTour,title:'Resumo do período',text:'Este painel apresenta escolas conectadas, visitas do dia e volume realizado no mês diretamente a partir da base.'},
      {selector:'.ure-module-grid',title:'Módulos de análise',text:'Acesse planejamento por supervisor, planejamento por escola, metas e filtros detalhados.'},
      {selector:'.ure-module[data-url="BS.html"]',prepare:showHomeForTour,title:'Supervisores planejamento',text:'Abra este módulo para comparar planejamento, execução e cobertura das escolas por supervisor.'},
      {selector:'#contentFrame',prepare:()=>showRealModule('BS.html'),title:'Planejamento por supervisor',text:'Na tela real, selecione o período e um supervisor ou mantenha Todos para comparar a equipe.'},
      {selector:'#contentFrame',prepare:()=>showRealModule('BS.html'),title:'Indicadores dos supervisores',text:'Veja planejadas, realizadas, cobertura, metas e a distribuição das visitas no calendário.'},
      {selector:'#contentFrame',prepare:()=>showRealModule('BS.html'),title:'Desempenho individual',text:'O detalhamento ajuda a identificar supervisores que precisam de acompanhamento.'},
      {selector:'.ure-module[data-url="BM.html"]',prepare:showHomeForTour,title:'Escolas planejamento',text:'Abra este módulo para analisar cada escola em relação ao planejamento e às visitas realizadas.'},
      {selector:'#contentFrame',prepare:()=>showRealModule('BM.html'),title:'Planejamento por escola',text:'Nesta tela real, selecione o período e consulte a cobertura das unidades escolares.'},
      {selector:'#contentFrame',prepare:()=>showRealModule('BM.html'),title:'Cenário das escolas',text:'Os indicadores mostram escolas visitadas, sem visita, planejamentos e metas alcançadas.'},
      {selector:'#contentFrame',prepare:()=>showRealModule('BM.html'),title:'Detalhamento por escola',text:'Compare visitas planejadas e realizadas, identifique atividades extras e escolas que exigem atenção.'},
      {selector:'.ure-module[data-url="meta.html"]',prepare:showHomeForTour,title:'Metas',text:'Este módulo acompanha metas mensais e semanais dos supervisores.'},
      {selector:'#contentFrame',prepare:()=>showRealModule('meta.html'),title:'Metas dos supervisores',text:'Esta é a tela correta de Metas. Escolha mês, ano e supervisor para analisar o resultado individual ou consolidado.'},
      {selector:'#contentFrame',prepare:()=>showRealModule('meta.html'),title:'Meta × realidade',text:'Compare a meta prevista, o realizado, o desempenho mensal e quantas visitas ainda faltam.'},
      {selector:'#contentFrame',prepare:()=>showRealModule('meta.html'),title:'Desempenho por supervisor',text:'A tabela detalha visitas, meta mensal, meta semanal e desempenho, como mostrado nesta página.'},
      {selector:'.ure-module[data-url="filtros.html"]',prepare:showHomeForTour,title:'Filtro',text:'Abra esta consulta para localizar registros específicos e extrair informações detalhadas.'},
      {selector:'#contentFrame',prepare:()=>showRealModule('filtros.html'),title:'Filtros de vistoria',text:'Na tela real, combine período, supervisor, escola, tipo de visita, status e ações realizadas.'},
      {selector:'#contentFrame',prepare:()=>showRealModule('filtros.html'),title:'Resultado da consulta',text:'A lista apresenta data, origem, supervisor, escola, status, ações ou justificativa e autor do registro.'},
      {selector:'#contentFrame',prepare:()=>showRealModule('filtros.html'),title:'Exportar os registros',text:'Depois de filtrar, use a exportação quando precisar trabalhar com o resultado fora do portal.'},
      {selector:'#themePickerButton',prepare:showHomeForTour,title:'Personalizar cores',text:'Escolha uma paleta mais confortável para leitura. A preferência fica memorizada neste navegador.'},
      {selector:'.ure-pulse',title:'Atividade das últimas semanas',text:'O gráfico mostra o volume diário de eventos das duas últimas semanas, com total, média e dias de maior movimento.'},
      {selector:'.ure-focus',title:'Prioridades de acompanhamento',text:'Veja escolas com meta não atingida, sem visita há mais de 15 dias, justificadas e registros aguardando validação.'},
      {selector:'.ure-validation-action',title:'Validar justificativas',text:'Este atalho abre a análise das justificativas enviadas. A gestão pode aprovar ou rejeitar cada solicitação.'},
      {selector:'.gestor-demo-justifications .gestor-demo-topbar',prepare:showJustificationDemo,title:'Tela de validação',text:'Aqui a gestão acompanha as justificativas pendentes, aprovadas e rejeitadas no período. Esta tela do Tour é apenas demonstrativa.'},
      {selector:'.gestor-demo-justifications .gestor-demo-kpis',prepare:showJustificationDemo,title:'Situação das justificativas',text:'Os indicadores mostram quantas justificativas aguardam decisão e quantas já foram aprovadas ou rejeitadas.'},
      {selector:'.gestor-demo-justifications .gestor-demo-row',prepare:showJustificationDemo,title:'Analisar antes de decidir',text:'Confira escola, supervisor, referência da meta e motivo informado. Depois, no sistema real, escolha Aprovar ou Rejeitar.',tip:'A aprovação concede o crédito previsto à meta; a rejeição mantém a escola na prioridade.'},
      {selector:'.ure-focus > button',prepare:hideManagementDemo,title:'Ver prioridades',text:'Este botão abre a relação completa das escolas que exigem atenção.'},
      {selector:'.gestor-demo-priority .gestor-demo-topbar',prepare:showPriorityDemo,title:'Tela de prioridades',text:'A página consolida as escolas que precisam de acompanhamento e permite atualizar ou extrair a relação em CSV.'},
      {selector:'.gestor-demo-rule',prepare:showPriorityDemo,title:'Regra de acompanhamento',text:'A regra explica por que uma escola entra na lista: meta não atingida, visita atrasada, justificativa ou validação pendente.'},
      {selector:'.gestor-demo-priority-kpis',prepare:showPriorityDemo,title:'Leitura do cenário',text:'Compare prioridades críticas, escolas sem visita há mais de 15 dias, validações aguardando análise e escolas dentro da regra.'},
      {selector:'.gestor-demo-priority-table',prepare:showPriorityDemo,title:'Investigar as escolas',text:'Pesquise uma escola ou use os filtros de classificação para entender o motivo da prioridade e acompanhar sua situação.'}
    ]
  };
  let steps=[],index=0,active=false,shades=[],focus,tooltip;
  const icon='<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="9"/><path d="M9.8 9a2.4 2.4 0 1 1 3.4 2.2c-.8.4-1.2.9-1.2 1.8M12 17h.01"/></svg>';
  const visible=el=>el&&!el.hidden&&el.getClientRects().length>0;
  const currentSteps=()=> (configs[page]||[]).map(item=>({...item,element:document.querySelector(item.selector)})).filter(item=>item.element&&(item.prepare||visible(item.element)));
  const userKey=()=>document.getElementById('userName')?.textContent?.trim()||'administrador';
  const storageKey=()=>`gestor-ese-tour:${userKey()}:v${VERSION}`;
  function removeTour(){shades.forEach(el=>el.remove());shades=[];focus?.remove();tooltip?.remove();focus=tooltip=null;active=false;document.removeEventListener('keydown',onKey);hideManagementDemo();if(moduleBlocker)moduleBlocker.hidden=true}
  function close(completed=false){if(completed){try{localStorage.setItem(storageKey(),'completed')}catch(_){}}removeTour()}
  function onKey(event){if(event.key==='Escape')close();if(event.key==='ArrowRight'){event.preventDefault();next()}if(event.key==='ArrowLeft'){event.preventDefault();previous()}}
  function ensureLayer(){if(shades.length)return;shades=Array.from({length:4},()=>{const el=document.createElement('div');el.className='gestor-tour-shade';document.body.appendChild(el);return el});focus=document.createElement('div');focus.className='gestor-tour-focus';document.body.appendChild(focus);tooltip=document.createElement('section');tooltip.className='gestor-tour-tooltip';tooltip.setAttribute('role','dialog');tooltip.setAttribute('aria-modal','true');document.body.appendChild(tooltip)}
  function position(){positionModuleBlocker();if(!active||!steps[index])return;const rect=steps[index].element.getBoundingClientRect(),pad=7,w=innerWidth,h=innerHeight,left=Math.max(0,rect.left-pad),top=Math.max(0,rect.top-pad),right=Math.min(w,rect.right+pad),bottom=Math.min(h,rect.bottom+pad);Object.assign(shades[0].style,{left:'0',top:'0',width:'100%',height:`${top}px`});Object.assign(shades[1].style,{left:'0',top:`${top}px`,width:`${left}px`,height:`${bottom-top}px`});Object.assign(shades[2].style,{left:`${right}px`,top:`${top}px`,width:`${w-right}px`,height:`${bottom-top}px`});Object.assign(shades[3].style,{left:'0',top:`${bottom}px`,width:'100%',height:`${h-bottom}px`});Object.assign(focus.style,{left:`${left}px`,top:`${top}px`,width:`${Math.max(0,right-left)}px`,height:`${Math.max(0,bottom-top)}px`});const tipRect=tooltip.getBoundingClientRect(),spaceBelow=h-bottom,tipTop=spaceBelow>tipRect.height+18?bottom+12:Math.max(12,top-tipRect.height-12),tipLeft=Math.min(Math.max(12,left),w-tipRect.width-12);Object.assign(tooltip.style,{left:`${tipLeft}px`,top:`${tipTop}px`})}
  function render(){const step=steps[index];if(!step)return;step.prepare?.();step.element.scrollIntoView({behavior:'smooth',block:'center',inline:'nearest'});tooltip.innerHTML=`<button class="gestor-tour-close" type="button" aria-label="Fechar guia">×</button><p class="kicker">Manual interativo</p><h2>${step.title}</h2><p>${step.text}</p>${step.tip?`<p class="tip">${step.tip}</p>`:''}<div class="gestor-tour-actions"><span class="gestor-tour-count">${index+1} de ${steps.length}</span><button class="gestor-tour-nav" data-action="previous" type="button" ${index===0?'disabled':''}>Anterior</button><button class="gestor-tour-nav primary" data-action="next" type="button">${index===steps.length-1?'Concluir':'Próximo'}</button></div>`;tooltip.querySelector('.gestor-tour-close').onclick=()=>close();tooltip.querySelector('[data-action="previous"]').onclick=previous;tooltip.querySelector('[data-action="next"]').onclick=next;setTimeout(position,260)}
  function start(){removeTour();if(page==='index.html')ensureManagementDemo();steps=currentSteps();if(!steps.length)return;active=true;index=0;ensureLayer();document.addEventListener('keydown',onKey);render()}
  function next(){if(index>=steps.length-1){close(true);return}index++;render()}
  function previous(){if(index>0){index--;render()}}
  function showWelcome(){if(document.querySelector('.gestor-welcome-backdrop'))return;const layer=document.createElement('div');layer.className='gestor-welcome-backdrop';layer.innerHTML='<section class="gestor-welcome" role="dialog" aria-modal="true" aria-labelledby="gestorWelcomeTitle"><div class="gestor-welcome-icon">?</div><p class="kicker">Bem-vindo ao Gestor-ESE</p><h2 id="gestorWelcomeTitle">Deseja conhecer o portal?</h2><p>Preparamos um guia rápido para apresentar os cadastros, indicadores e ferramentas de acompanhamento. Você pode iniciar agora ou acessar novamente pelo botão <strong>Ajuda / Tour</strong>.</p><div class="gestor-welcome-actions"><button type="button" data-choice="later">Fazer depois</button><button class="primary" type="button" data-choice="start">Iniciar tour</button></div></section>';document.body.appendChild(layer);layer.querySelector('[data-choice="later"]').onclick=()=>{try{localStorage.setItem(storageKey(),'later')}catch(_){}layer.remove()};layer.querySelector('[data-choice="start"]').onclick=()=>{layer.remove();start()}}
  function offerFirstTour(){if(page!=='index.html'||visible(document.querySelector('#loginScreen'))||!visible(document.querySelector('#homeView')))return;try{if(localStorage.getItem(storageKey()))return}catch(_){}showWelcome()}
  function mount(){if(!(configs[page]||[]).length)return;const help=document.createElement('button');help.type='button';help.className='gestor-help-button';help.innerHTML=`${icon}<span>Ajuda / Tour</span>`;help.setAttribute('aria-haspopup','menu');const menu=document.createElement('div');menu.className='gestor-tour-menu';menu.hidden=true;menu.innerHTML='<strong>Manual interativo</strong><button type="button">Iniciar guia desta tela</button>';document.body.append(menu,help);help.onclick=()=>{menu.hidden=!menu.hidden};menu.querySelector('button').onclick=()=>{menu.hidden=true;start()};document.addEventListener('click',event=>{if(!menu.hidden&&!menu.contains(event.target)&&!help.contains(event.target))menu.hidden=true});addEventListener('resize',position,{passive:true});addEventListener('scroll',position,{passive:true});new MutationObserver(offerFirstTour).observe(document.body,{subtree:true,attributes:true,attributeFilter:['hidden'],childList:true,characterData:true});offerFirstTour()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
  window.GestorESETour={start,close};
})();
